---
- name: Install dependencies
  apt:
    name:
      - wget
      - adduser
      - libfontconfig1
    state: present
    update_cache: yes

- name: Download Grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana-10.4.2.linux-amd64.tar.gz
    dest: /tmp/grafana.tar.gz
    checksum: sha256:abc123...  # Add actual checksum if needed

- name: Extract Grafana
  unarchive:
    src: /tmp/grafana.tar.gz
    dest: /opt
    remote_src: no
    creates: /opt/grafana-10.4.2

- name: Verify extraction
  command: ls -la /opt/grafana-10.4.2/bin/
  register: grafana_bin
  changed_when: false

- name: Debug extraction
  debug:
    var: grafana_bin.stdout

- name: Create grafana user
  user:
    name: grafana
    system: yes
    shell: /bin/false

- name: Create data and log directories
  file:
    path: "{{ item }}"
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'
  loop:
    - /var/lib/grafana
    - /var/log/grafana

- name: Copy Grafana binary
  copy:
    remote_src: yes
    src: /opt/grafana-10.4.2/bin/grafana-server
    dest: /usr/local/bin/grafana-server
    mode: '0755'
    owner: grafana
    group: grafana

# ... rest of the tasks remain the same
