---
- name: Ensure Docker is installed
  include_role:
    name: docker

- name: Create directory for Grafana data
  file:
    path: /opt/grafana/data
    state: directory
    mode: '0755'

- name: Run Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    volumes:
      - "/opt/grafana/data:/var/lib/grafana"
    env:
      GF_SECURITY_ADMIN_PASSWORD: "admin123"
      GF_SECURITY_ADMIN_USER: "admin"

- name: Wait for Grafana to start
  wait_for:
    port: 3000
    delay: 10
    timeout: 120

- name: Verify Grafana is accessible
  command: docker logs grafana
  register: grafana_logs
  changed_when: false

- name: Show Grafana status
  debug:
    msg: "Grafana container started. Access at: http://{{ inventory_hostname }}:3000 (admin/admin123)
