---
- name: Deploy Node Exporters on all servers
  hosts: test,prod
  become: true
  roles:
    - node_exporter

- name: Deploy Monitoring Stack
  hosts: monitoring
  become: true
  roles:
    - prometheus
    - grafana

- name: Verify Monitoring Setup
  hosts: monitoring
  become: true
  tasks:
    - name: Check Prometheus is running
      systemd:
        name: prometheus
        state: started

    - name: Check Grafana is running
      systemd:
        name: grafana
        state: started

    - name: Test Prometheus endpoint
      uri:
        url: http://localhost:9090/api/v1/status/config
        method: GET
        status_code: 200
      register: prometheus_test

    - name: Test Grafana endpoint
      uri:
        url: http://localhost:3000/api/health
        method: GET
        status_code: 200
      register: grafana_test

    - name: Show monitoring URLs
      debug:
        msg:
          - "Prometheus: http://{{ inventory_hostname }}:9090"
          - "Grafana: http://{{ inventory_hostname }}:3000 (admin/admin123)"
          - "Node Exporter: http://{{ inventory_hostname }}:9100/metrics"
