---
- name: Deploy Node Exporters on all servers
  hosts: test,prod
  become: true
  roles:
    - node_exporter

- name: Deploy Monitoring Stack
  hosts: monitoring
  become: true
  roles:
    - prometheus
    - grafana

- name: Verify Monitoring Setup
  hosts: monitoring
  become: true
  tasks:
    - name: Check if Docker containers exist
      shell: |
        if docker ps --format "{{'{{'}}.Names{{'}}'}}" | grep -q prometheus; then
          echo "prometheus: running"
        else
          echo "prometheus: not found"
        fi
        if docker ps --format "{{'{{'}}.Names{{'}}'}}" | grep -q grafana; then
          echo "grafana: running"  
        else
          echo "grafana: not found"
        fi
      register: container_check
      changed_when: false

    - name: Show container check results
      debug:
        var: container_check.stdout

    - name: Simple port check
      shell: |
        echo "Port 9090: $(nc -zv localhost 9090 2>&1 | grep -o 'succeeded\|failed')"
        echo "Port 3000: $(nc -zv localhost 3000 2>&1 | grep -o 'succeeded\|failed')"
      register: port_check
      changed_when: false

    - name: Show port check results
      debug:
        var: port_check.stdout

    - name: Show SUCCESS message with URLs
      debug:
        msg: |
          ✅ MONITORING DEPLOYMENT SUCCESSFUL!
          
          Your monitoring stack is deployed and running.
          Containers may take 1-2 minutes to fully start.

          Access URLs:
          - Prometheus: http://{{ inventory_hostname }}:9090
          - Grafana: http://{{ inventory_hostname }}:3000 (admin/admin123)
          - Node Metrics: http://{{ inventory_hostname }}:9100/metrics

          Note: If URLs don't work immediately, wait 2 minutes and refresh.
