all:
  children:
    dev:
      hosts:
        dev-server-1:
          ansible_host: 3.109.133.94
          ansible_user: devops
    stage:
      hosts:
        stage-server-1:
          ansible_host: 3.7.37.177
          ansible_user: devops
    prod:
      hosts:
        prod-server-1:
          ansible_host: 13.200.237.18
          ansible_user: devops

