---
- name: Ensure Docker is installed
  include_role:
    name: docker

- name: Clean up existing Prometheus containers
  shell: |
    docker rm -f prometheus 2>/dev/null || true
    sudo fuser -k 9090/tcp 2>/dev/null || true
    docker system prune -f 2>/dev/null || true
    echo "Cleanup completed"
  ignore_errors: yes
  changed_when: false

- name: Create directories for Prometheus
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/prometheus
    - /opt/prometheus/data
  ignore_errors: yes

- name: Create Prometheus configuration
  copy:
    dest: /opt/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['localhost:9100']
        - job_name: 'banking-app'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['test-server:8080', 'prod-server:8080']
    owner: root
    group: root
    mode: '0644'

- name: Run Prometheus container (idempotent)
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - "/opt/prometheus:/etc/prometheus"
      - "/opt/prometheus/data:/prometheus"
    pull: yes
    command: --config.file=/etc/prometheus/prometheus.yml --web.listen-address=0.0.0.0:9090

- name: Wait for Prometheus to start
  wait_for:
    port: 9090
    delay: 10
    timeout: 120
  ignore_errors: yes

- name: Verify Prometheus health
  uri:
    url: http://localhost:9090/-/healthy
    method: GET
    status_code: 200
    timeout: 30
  register: prometheus_health
  until: prometheus_health.status == 200
  retries: 10
  delay: 5
  ignore_errors: yes

- name: Show Prometheus status
  debug:
    msg: "Prometheus container started. Access at: http://{{ inventory_hostname }}:9090"
